$(function(){
	$('#side').height($(window).height());
	$('.hb.selection.dropdown')
	.dropdown()
	;	
	$('.hb.checkbox')
	.checkbox()
	;
	$('#tab1>.item')
	.tab({
		history:false,
		onTabLoad:function(){
			$('.hb.tab').eq(0).addClass('active');
		}
	});
	$('#size>.item').click(function(){
		var dataTab=$(this).attr('data-tab');
		$(this).addClass('active').siblings().removeClass('active');
		$('.hb.tab').each(function(){
			if($(this).attr('data-tab')==dataTab){
				$(this).addClass('active').siblings().removeClass('active');
			}
		});
	});
});